spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/mladenoff
          jwk-set-uri: ${spring.security.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  application:
    name: keycloak

server:
  port: 8081
